### ISSUE TITLE
Work on BIOS version F.71

### ISSUE THREAD

**Issue by VuBoi** [SkyrilHD/HP-8570W-Hackintosh#13]
Laptop HP 8570w | K2000M 2GB | 16GB Ram | CPU I7 3820QM
- macOS: Catalina 10.15.7
- BIOS Version: F71
Every work smooth , Thank you so much
![alt](https://i.imgur.com/BVoPgRy.jpg)
![alt](https://i.imgur.com/6WAubSv.jpg)

**Comment by SkyrilHD** [comment]
Thank you very much for confirming F.71

**Comment by mathgonzlez** [comment]
mine stuck at 3min remaining. 
same setup but with k1000m

**Comment by SkyrilHD** [comment]
Clear your NVRAM and set the BIOS settings as described in the README. Make sure you formatted the drive as APFS with GUID partition table (GPT)
