### ISSUE TITLE
VoodooPS2TrackPad: identify TochPad command return incorrect type 2

### ISSUE THREAD

**Issue by pishguy** [SkyrilHD/HP-8570W-Hackintosh#16]
during boot process i get this message and couldn't skip or return after this action

![WhatsApp Image 2021-07-15 at 08 37 57](https://user-images.githubusercontent.com/6617583/125728963-532bcc99-2662-42e0-9d52-45afe1572120.jpeg)

**Comment by SkyrilHD** [comment]
For some reason, you have ACPI errors. Which BIOS version are you on and did you apply the BIOS settings provided in README?

**Comment by MahdiPishguy** [comment]
@SkyrilHD how can i find out `BIOS version`?

**Comment by SkyrilHD** [comment]
@MahdiPishguy Go to the BIOS and you should be able to see it. e.g. F.71
