### ISSUE TITLE
Incorrect VoodooPs2Trackpad

### ISSUE THREAD

**Issue by pishguy** [SkyrilHD/HP-8570W-Hackintosh#17]
During boot up I get this message and it doesn't continue 

VoodooPS2Teackpad: identify Touchpad command returned incorrect byte 2 (of 3) : 0x00

**Comment by SkyrilHD** [comment]
Can you post a picture of the verbose screen? I doubt it is because of VoodooPS2

**Comment by pishguy** [comment]
I uploaded screen shot
![IMG_20210807_193512](https://user-images.githubusercontent.com/6617583/128608539-7cbe6fab-27fa-4218-9faf-23dc59655a45.jpg)

**Comment by SkyrilHD** [comment]
The issue I assume is the ACPI error 'PNOT'. Make sure you set your BIOS settings correctly (you can check the README to double check)

**Comment by pishguy** [comment]
@SkyrilHD 

https://github.com/SkyrilHD/HP-8570W-Hackintosh#generating-your-own-serial-and-editing-rom

is this your meant?

**Comment by SkyrilHD** [comment]
Nope, this: https://github.com/SkyrilHD/HP-8570W-Hackintosh#bios-settings

**Comment by pishguy** [comment]
@SkyrilHD resolved thanks so much
