### ISSUE TITLE
Bless to place boot files failed

### ISSUE THREAD

**Issue by pishguy** [SkyrilHD/HP-8570W-Hackintosh#18]
I'm not sure about this problem that this is relative with BIOS settings, but after resolve many problems during installing MacOs i get this error now

![IMG_20210807_194632](https://user-images.githubusercontent.com/6617583/128609268-aa0e4c70-7560-411f-bafd-f9f7bd09a7b8.jpg)

**Comment by SkyrilHD** [comment]
Make sure you formatted the drive as GUID partition table and APFS (NOT macOS Journaled)

**Comment by pishguy** [comment]
@SkyrilHD 

yes i'm sure


![Screenshot 2021-08-07 223305](https://user-images.githubusercontent.com/6617583/128609873-1b3d8a99-35ce-43b8-b6a6-17508081d1b8.png)

**Comment by SkyrilHD** [comment]
Very weird. I suggest recreating your installer.

Here is a guide:
- macOS: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html
- Windows: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html#downloading-macos

**Comment by pishguy** [comment]
@SkyrilHD i get error again :(

i have this problem on both of OC and Clover, after getting this error i tested installing on real hard disk which that's into laptop not external hard drive, i get error again :( 


![IMG_20210807_233839](https://user-images.githubusercontent.com/6617583/128611826-84c7c650-1e5a-4ec1-901b-886c0b79a024.jpg)
![IMG_20210807_233800](https://user-images.githubusercontent.com/6617583/128611828-f2e97356-553c-4bf4-aeef-dd55393f8930.jpg)

**Comment by SkyrilHD** [comment]
Please don't use a distro. Vanilla install should fix the problem

**Comment by SkyrilHD** [comment]
Any update?
