### ISSUE TITLE
NO-AUDIO

### ISSUE THREAD

**Issue by ruben-p** [SkyrilHD/HP-8570W-Hackintosh#4]
Thanks for this, i'm testing on 2570p an boot with this OC.
The major problem is no audio, i tested adding alcid=12 and others on bootargs but not work
any solution?

**Comment by SkyrilHD** [comment]
We got audio working by using VoodooHDA instead of AppleALC

**Comment by ruben-p** [comment]
I finally full working OC loading DSDT generated from this method:
https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator/releases

Works all:
sound
keys, brithgness adjust, sound
battery indicator

**Comment by ruben-p** [comment]
https://gofile.io/d/6xJxVF

Its for 2570p full folder

**Comment by SkyrilHD** [comment]
Thank you very much!
