### ISSUE TITLE
EFI supported Mojave? 

### ISSUE THREAD

**Issue by MahdiPishguy** [SkyrilHD/HP-8570W-Hackintosh#5]
I successful installed Mojave and my question is can I copy EFI folder to installed partition?

It can't detect wifi and sound drivers

**Comment by SkyrilHD** [comment]
Yes, you can copy the EFI folder to the installed partition.

What WiFi card is in your laptop? Audio should work, could you check what your Codec is?

**Comment by MahdiPishguy** [comment]
> Yes, you can copy the EFI folder to the installed partition.
> 
> What WiFi card is in your laptop? Audio should work, could you check what your Codec is?

My laptop is `Elitebook 8570w` and wifi and sound card not working when i installed Mojave and how can i check whats `Codec`?

**Comment by SkyrilHD** [comment]
1. What is your WiFi? (Intel, Broadcom or Atheros)

2. Sorry about codec, I meant the PCI path.

2.1. Could you try typing this in Terminal? `kextstat | grep -E "AppleHDA|AppleALC|Lilu"` The output should be the three kexts

2.2. Can you send me an output of gfxutil? https://github.com/acidanthera/gfxutil/releases

2.3. Also could you send an IOReg, so I can look if the driver even loads. https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-302.zip

**Comment by MahdiPishguy** [comment]
@SkyrilHD i'm sorry i don't have more information for what you want from me. as you say in number 1, i don't know really how can i found out?

**Comment by SkyrilHD** [comment]
Well, did you change your WiFi card or not? You can also check your WiFi card in Windows too if you have it installed

**Comment by MahdiPishguy** [comment]
@SkyrilHD i dont change any wifi during installation or using installed mac, i have only one external `wifi` as named `TP LINK tl-wn727n` and i want to know can i installed HP internal wifi card?

**Comment by SkyrilHD** [comment]
Can you say the name of your WiFi card so I can answer your question

**Comment by MahdiPishguy** [comment]
@SkyrilHD ok. let me found out how can i know whats my laptop wifi card name

**Comment by MahdiPishguy** [comment]
@SkyrilHD i'm not sure, but i think wifi is `Qualcomm Atheros AR9485 1x1 802.11b/g/n`

**Comment by SkyrilHD** [comment]
if it is an Atheros AR9485 then it is supported. you only need to add the kexts which can be found here: https://github.com/chunnann/ATH9KFixup

**Comment by MahdiPishguy** [comment]
Hi again. i listed chip set  by `hwinfo`, can be helpful?


WIFI:
```
21: PCI 2500.0: 0282 WLAN controller
  [Created at pci.386]
  Unique ID: S6TQ.sFdaNCNfTFB
  Parent ID: Z7uZ.2fD530kY+A1
  SysFS ID: /devices/pci0000:00/0000:00:1c.3/0000:25:00.0
  SysFS BusID: 0000:25:00.0
  Hardware Class: network
  Device Name: "WLAN"
  Model: "Intel Centrino Advanced-N 6205 AGN"
  Vendor: pci 0x8086 "Intel Corporation"
  Device: pci 0x0082 "Centrino Advanced-N 6205 [Taylor Peak]"
  SubVendor: pci 0x8086 "Intel Corporation"
  SubDevice: pci 0x1301 "Centrino Advanced-N 6205 AGN"
  Revision: 0x34
  Driver: "iwlwifi"
  Driver Modules: "iwlwifi"
  Device File: wlo1
  Features: WLAN
  Memory Range: 0xd9100000-0xd9101fff (rw,non-prefetchable)
  IRQ: 33 (731374 events)
  HW Address: 60:67:20:8f:5d:f4
  Permanent HW Address: 60:67:20:8f:5d:f4
  Link detected: yes
  WLAN channels: 1 2 3 4 5 6 7 8 9 10 11 36 40 44 48 52 56 60 64 100 104 108 112 116 120 124 128 132 136 140 149 153
  WLAN frequencies: 2.412 2.417 2.422 2.427 2.432 2.437 2.442 2.447 2.452 2.457 2.462 5.18 5.2 5.22 5.24 5.26 5.28 5.3 5.32 5.5 5.52 5.54 5.56 5.58 5.6 5.62 5.64 5.66 5.68 5.7 5.745 5.765
  WLAN encryption modes: WEP40 WEP104 TKIP CCMP
  WLAN authentication modes: open sharedkey wpa-psk wpa-eap
  Module Alias: "pci:v00008086d00000082sv00008086sd00001301bc02sc80i00"
  Driver Info #0:
    Driver Status: iwlwifi is active
    Driver Activation Cmd: "modprobe iwlwifi"
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #26 (PCI bridge)
```



AUDIO:

```
25: PCI 1b.0: 0403 Audio device
  [Created at pci.386]
  Unique ID: u1Nb.f3fwpYvujv4
  SysFS ID: /devices/pci0000:00/0000:00:1b.0
  SysFS BusID: 0000:00:1b.0
  Hardware Class: sound
  Model: "Intel 7 Series/C216 Chipset Family High Definition Audio Controller"
  Vendor: pci 0x8086 "Intel Corporation"
  Device: pci 0x1e20 "7 Series/C216 Chipset Family High Definition Audio Controller"
  SubVendor: pci 0x103c "Hewlett-Packard Company"
  SubDevice: pci 0x176b 
  Revision: 0x04
  Driver: "snd_hda_intel"
  Driver Modules: "snd_hda_intel"
  Memory Range: 0xd9430000-0xd9433fff (rw,non-prefetchable)
  IRQ: 34 (1776 events)
  Module Alias: "pci:v00008086d00001E20sv0000103Csd0000176Bbc04sc03i00"
  Driver Info #0:
    Driver Status: snd_hda_intel is active
    Driver Activation Cmd: "modprobe snd_hda_intel"
  Config Status: cfg=new, avail=yes, need=no, active=unknown





35: PCI 100.1: 0403 Audio device
  [Created at pci.386]
  Unique ID: NXNs.PZRLPJiX0L2
  Parent ID: vSkL.DQccioWPun3
  SysFS ID: /devices/pci0000:00/0000:00:01.0/0000:01:00.1
  SysFS BusID: 0000:01:00.1
  Hardware Class: sound
  Model: "nVidia GK107 HDMI Audio Controller"
  Vendor: pci 0x10de "nVidia Corporation"
  Device: pci 0x0e1b "GK107 HDMI Audio Controller"
  SubVendor: pci 0x103c "Hewlett-Packard Company"
  SubDevice: pci 0x176b 
  Revision: 0xa1
  Driver: "snd_hda_intel"
  Driver Modules: "snd_hda_intel"
  Memory Range: 0xd9000000-0xd9003fff (rw,non-prefetchable)
  IRQ: 17 (224 events)
  Module Alias: "pci:v000010DEd00000E1Bsv0000103Csd0000176Bbc04sc03i00"
  Driver Info #0:
    Driver Status: snd_hda_intel is active
    Driver Activation Cmd: "modprobe snd_hda_intel"
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #20 (PCI bridge)
```

**Comment by SkyrilHD** [comment]
Your WiFi card is an Intel Centrino Advanced-N 6205. I don't know if it supported by the kext but you can try [Itlwm](https://github.com/OpenIntelWireless/itlwm)

And Sound does look fine to me.

**Comment by MahdiPishguy** [comment]
command `kextstat | grep -E "AppleHDA|AppleALC|Lilu"` output:

```
   17    6 0xffffff7f80c91000 0x22000    0x22000    as.vit9696.Lilu (1.2.8) 54014689-C8DA-318B-84F4-944BBA7AD2AC <8 6 5 3 2 1>
   27    0 0xffffff7f812bf000 0xdf000    0xdf000    as.vit9696.AppleALC (1.3.3) B60FCBAF-6BC2-36EF-A1E6-D5BE2863C35B <17 13 8 6 5 3 2 1>
```

**Comment by SkyrilHD** [comment]
Seems like AppleHDA does not want to load. bummer. As a workaround, you can use VoodooHDA instead of AppleALC. We used that first, then the sound somehow worked with AppleALC.

**Comment by MahdiPishguy** [comment]
> Your WiFi card is an Intel Centrino Advanced-N 6205. I don't know if it supported by the kext but you can try [Itlwm](https://github.com/OpenIntelWireless/itlwm)
> 
> And Sound does look fine to me.

after installing this driver i have this data in system information 

```
  Software Versions:
  CoreWLAN:	13.0 ((null))
  CoreWLANKit:	13.0 ((null))
  Menu Extra:	13.0 ((null))
  System Information:	12.0 (1500)
  IO80211 Family:	12.0 (1200.12.2b1)
  Diagnostics:	1.0 (910)
  AirPort Utility:	Not Installed
```

but wifi doesn't work

**Comment by SkyrilHD** [comment]
Depends what you installed. If you installed itlwm, then you have to download Heliport too. Airportitlwm makes it compatible system-wide.

**Comment by MahdiPishguy** [comment]
> Depends what you installed. If you installed itlwm, then you have to download Heliport too. Airportitlwm makes it compatible system-wide.

could you help me how can i configure the itlwm.kext and injection info in `config.plist`

thanks

**Comment by SkyrilHD** [comment]
Closing this issue as 0.6.6 has been made from scratch and audio is confirmed working
