### ISSUE TITLE
replacing EFI cause of don't boot hackintosh

### ISSUE THREAD

**Issue by MahdiPishguy** [SkyrilHD/HP-8570W-Hackintosh#6]
after successful installing Mojave and replacing the repository `EFI` to mac partition, after restarting system, mac hangout on apple logo and couldn't boot

**Comment by SkyrilHD** [comment]
Can you add `-v` as a boot-arg and send a picture where it hangs?

**Comment by MahdiPishguy** [comment]
How can I add this flag? Pressing `spacebar` key doesn't show options and
cause of refreshing clover boot menu.

**Comment by SkyrilHD** [comment]
Open the config.plist with a Plist editor of your choice e.g. XCode and add `-v` in NVRAM > 7C436110-AB2A-4BBB-A880-FE41995C9F82 > boot-arg

https://github.com/SkyrilHD/HP-8570W-Hackintosh/blob/267e323eba3c47cabf9d3c7d6af22f1a43bb5c90/EFI/OC/config.plist#L1729-L1730

**Comment by MahdiPishguy** [comment]
I see looping this message

```
Disk1s2 media is not present. 
```

![IMG_20210109_221714](https://user-images.githubusercontent.com/6617583/104106145-c2332280-52c8-11eb-8540-3fa005174c8c.jpg)

**Comment by SkyrilHD** [comment]
Any pictures before the loop happens? I guess this happens when a driver is not loaded (?)

**Comment by MahdiPishguy** [comment]
There are many message which I can't take a picture. I think I should take
a video instead


Can I send video?

**Comment by SkyrilHD** [comment]
yes of course

**Comment by MahdiPishguy** [comment]
i uploaded video and you can download it from [this link](http://www.nebrass.ir/efi.mp4)

i installed mac on Flash Disk(32GB)

**Comment by MahdiPishguy** [comment]
Could you found out what happened?

**Comment by SkyrilHD** [comment]
Looking at this video, I could see some issues but shouldn't occur.

For example:
- In 0:32, there are prelink injection errors.
- Also in 0:39, there are ACPI errors visible.

So based on this, I might had issues when you downloaded the EFI. Maybe the EFI is corrupted. You could try disabling SSDT-FANORIG.aml and SSDT-8x70.aml in the config.plist file. "ACPI>Add" Just set Enabled to False. Also try disabling unnecessary kexts which you cannot use: AirportBrcmFixup.kext, ACPIBatteryManager.kext, BrcmBluetoothInjector.kext, BrcmFirmwareData.kext, BrcmPatchRAM3.kext, HSSDBlockStorage.kext, JMB38X.kext.

**Comment by MahdiPishguy** [comment]
I changed them, but not any change. i uploaded `config.plist` could you see this file content?

http://paste.debian.net/1180587/

**Comment by SkyrilHD** [comment]
You did it wrong. You renamed Enabled to false but you have to set the Boolean to false.

**Comment by SkyrilHD** [comment]
Closing this issue as 0.6.6 has been made from scratch and boot works without an issue
